#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# i3 dir
idir="$HOME/.config/i3"

# Export desktop session
export XDG_CURRENT_DESKTOP='i3'

# Kill already running process
_ps=(xsettingsd xcape)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Lauch xsettingsd daemon (if available)
if command -v xsettingsd >/dev/null 2>&1; then
    xsettingsd --config="$idir"/xsettingsd &
else
    gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-mauve-standard+default"
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
    gsettings set org.gnome.desktop.interface font-name "Ubuntu 11"
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
    xfconf-query -c xsettings -p /Net/ThemeName -s "catppuccin-mocha-mauve-standard+default" --create -t string 2>/dev/null
    xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark" --create -t string 2>/dev/null
    xfconf-query -c xsettings -p /Gtk/FontName -s "Ubuntu 11" --create -t string 2>/dev/null
fi

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
feh --bg-scale -cover "$idir"/theme/wallpaper

# Lauch notification daemon
"$idir"/scripts/i3_dunst

# Lauch polybar
"$idir"/scripts/i3_bar

# Lauch compositor
"$idir"/scripts/i3_comp

# Start mpd
exec mpd &
