#!/usr/bin/env bash

# Скрипт керування яскравістю через brightnessctl

case "$1" in
    --get)
        brightnessctl get
        ;;
    --inc)
        brightnessctl set +10%
        ;;
    --dec)
        brightnessctl set 10%-
        ;;
    --get-icon)
        BRIGHTNESS=$(brightnessctl get)
        MAX=$(brightnessctl max)
        PERCENT=$((BRIGHTNESS * 100 / MAX))
        
        if [ "$PERCENT" -gt 75 ]; then
            echo "󰃠"
        elif [ "$PERCENT" -gt 50 ]; then
            echo "󰃟"
        elif [ "$PERCENT" -gt 25 ]; then
            echo "󰃞"
        else
            echo "󰃝"
        fi
        ;;
    *)
        echo "Usage: $0 {--get|--inc|--dec|--get-icon}"
        exit 1
        ;;
esac
