#!/usr/bin/env bash

# Скрипт керування гучністю через pactl

case "$1" in
    --get)
        pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -1
        ;;
    --inc)
        pactl set-sink-volume @DEFAULT_SINK@ +5%
        ;;
    --dec)
        pactl set-sink-volume @DEFAULT_SINK@ -5%
        ;;
    --toggle)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;
    --get-icon)
        MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -o 'yes')
        if [ "$MUTED" == "yes" ]; then
            echo "󰝟"
        else
            VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -1)
            if [ "$VOLUME" -gt 50 ]; then
                echo "󰕾"
            elif [ "$VOLUME" -gt 0 ]; then
                echo "󰖀"
            else
                echo "󰕿"
            fi
        fi
        ;;
    *)
        echo "Usage: $0 {--get|--inc|--dec|--toggle|--get-icon}"
        exit 1
        ;;
esac
