# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Clipboard manager (Cliphist)
# Record text to history
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
# Record images to history
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store

# Blue light filter (Sunset)
exec-once = uwsm-app -- hyprsunset

# Automatic theme switcher (Runs on startup to set current theme)
exec-once = /home/arch/.local/bin/omarchy-theme-auto-switch
exec-once = hyprctl keyword decoration:screen_shader /home/arch/.config/hypr/shaders/grayscale.glsl
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
