# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
#bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
#bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
#bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
#bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
#bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
#bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
#bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
#bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
#bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
#bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
#bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
#bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
#bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden-desktop

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bind = SUPER, D, exec, uwsm-app -- chromium --app="https://ticktick.com/webapp/"
bind = SUPER, A, exec, uwsm-app -- chromium --app="https://notebooklm.google.com/"
bind = SUPER, S, exec, uwsm-app -- chromium --app="https://open.spotify.com/"

bind = SUPER_SHIFT, C, exec, uwsm-app -- chromium --app="https://calendar.google.com"
bind = SUPER_SHIFT, E, exec, uwsm-app -- chromium --app="https://mail.google.com"
bind = SUPER_SHIFT, Y, exec, uwsm-app -- chromium --app="https://youtube.com/"
bind = SUPER_SHIFT, W, exec, uwsm-app -- chromium --app="https://web.whatsapp.com/"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE

# -- System & Menus --
bindr = SUPER, Super_L, exec, omarchy-launch-walker
bind  = SUPER, Space, exec, omarchy-menu
bind  = SUPER, R, exec, hyprctl reload
bind  = SUPER, Slash, exec, omarchy-menu-keybindings
bind  = SUPER_ALT, T, exec, omarchy-menu background

# -- Apps (Overrides) --
bindd = CTRL SHIFT, Escape, Task Manager, exec, omarchy-launch-tui btop
bind = SUPER, Return, exec, uwsm-app -- xdg-terminal-exec
bind = SUPER, T, exec, uwsm-app -- Telegram
bind = SUPER, E, exec, uwsm-app -- nautilus --new-window
bind = SUPER, B, exec, omarchy-launch-browser
bind = SUPER, C, exec, omarchy-launch-editor
bind = SUPER, I, exec, systemsettings || gnome-control-center
bind = CTRL_SHIFT, Escape, exec, gnome-system-monitor || btop

# -- Screenshots & OCR --
bind = SUPER_SHIFT, S, exec, hyprshot -m region --clipboard-only
bind = SUPER_SHIFT, X, exec, grim -g "$(slurp)" - | tesseract stdin stdout -l ukr+eng+deu+rus | wl-copy
bind = SUPER_SHIFT, C, exec, hyprpicker -a
