# Конфігурація фільтра синього світла за часом
# 07:00 - Повернення до нормального кольору
profile {
    time = 07:00
    identity = true
}

# 20:00 - Активуємо теплий колір (фільтр синього світла) до 00:00
profile {
    time = 20:00
    temperature = 3500
}

# 00:00 - Повертаємо дещо прохолодніше, але все ще приємно для очей до ранку
profile {
    time = 00:00
    temperature = 5000
}
