[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout.css'
output_path = '~/.config/wlogout/style.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty || true'

[templates.cava]
input_path = '~/.config/matugen/templates/cava'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava || true'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = '~/.config/hypr/scripts/reload-gtk.sh >/dev/null 2>&1 || true'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5]
input_path = '~/.config/matugen/templates/qt_colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6]
input_path = '~/.config/matugen/templates/qt_colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.pywal]
input_path = '~/.config/matugen/templates/pywal.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update >/dev/null 2>&1 || true'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs >/dev/null 2>&1 || true'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.obs]
input_path = '~/.config/matugen/templates/obs.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/.config/obsidian/themes/matugen-dynamic.css'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'

[templates.vscode]
input_path = "~/.config/matugen/templates/vscode-colors.json"
output_path = "~/.cache/matugen/vscode-colors"

[templates.zed]
input_path = "~/.config/matugen/templates/vscode-colors.json"
output_path = "~/.cache/matugen/vscode-colors"

[templates.kvantum_kvconfig]
input_path = '~/.config/matugen/templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pgrep -x ghostty >/dev/null && pkill -SIGUSR2 ghostty || true'

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock-colors.conf"
